version: 2

registries:
  fortawesome:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: ${{ secrets.FONTAWESOME_TOKEN }}

updates:
  - package-ecosystem: npm
    registries:
      - fortawesome
    directory: /
    schedule:
      interval: daily
      time: '05:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 30

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '05:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'ci/cd'
      include: 'scope'
    open-pull-requests-limit: 30

  - package-ecosystem: npm
    directory: /tools/
    schedule:
      interval: daily
      time: '05:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'tools'
      include: 'scope'
    open-pull-requests-limit: 30
